[project]
name = "pyflink-state"
version = "0.1.0"
description = "Python state processor for Flink"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "py4j",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "ty",
]
